spring:
  data:
    mongodb:
      uri: mongodb_uri
      database: journaldb
      auto-index-creation: true
server:
  port: 8081
  servlet:
    context-path: /journal
mail:
  host: smtp.gmail.com
  port: 587
  username: mail@gmail.com
  password: password
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
weather:
  api:
    key: api_key